version: '3.8'
services:

  ollama:
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    volumes:
      - ./docker/ollama/entrypoint.sh:/entrypoint.sh
      - ./docker/tmp/ollama:/root/.ollama
    pull_policy: always
    tty: true
    restart: always
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
    networks:
      - ollama-docker
    entrypoint: ["/usr/bin/bash", "/entrypoint.sh"]
    labels:
      org.springframework.boot.service-connection: ollama

  ollama-webui:
    image: ghcr.io/open-webui/open-webui:main
    volumes:
      - ./docker/tmp/ollama-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - 8089:8080
    environment: # https://docs.openwebui.com/getting-started/env-configuration#default_models
      - OLLAMA_BASE_URLS=http://host.docker.internal:11434 #comma separated ollama hosts
      - ENV=dev
      - WEBUI_AUTH=False
      - WEBUI_NAME=valiantlynx AI
      - WEBUI_URL=http://localhost:8080
      - WEBUI_SECRET_KEY=t0p-s3cr3t
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    networks:
      - ollama-docker
    labels:
      org.springframework.boot.service-connection: ollama-ui

networks:
  ollama-docker:
    external: false